name: build-and-cache

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write # 必须：允许上传编译好的 NuGet 包

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      # 核心：设置二进制来源为 GitHub Packages
      VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json,readwrite"

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Checkout vcpkg
        uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          path: vcpkg

      - name: Install mono
        run: |
          sudo apt-get update
          sudo apt-get install -y mono-complete

      - name: Bootstrap vcpkg
        run: ${{ env.VCPKG_ROOT }}/bootstrap-vcpkg.sh

      - name: Add NuGet sources (Use PAT)
        shell: bash
        env:
          VCPKG_EXE: ${{ env.VCPKG_ROOT }}/vcpkg
          USERNAME: ${{ github.repository_owner }}
          FEED_URL: "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        run: |
          NUGET_EXE=$(${{ env.VCPKG_EXE }} fetch nuget | tail -n 1)
        
          mono $NUGET_EXE sources add \
            -Source "${{ env.FEED_URL }}" \
            -StorePasswordInClearText \
            -Name "GitHubPackages" \
            -UserName "${{ env.USERNAME }}" \
            -Password "${{ secrets.VCPKG_PAT_TOKEN }}"
          
          mono $NUGET_EXE setapikey "${{ secrets.VCPKG_PAT_TOKEN }}" \
            -Source "${{ env.FEED_URL }}"
      - name: Configure CMake
        run: |
          cmake -B build \
          -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" \
          -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release